"""Unit tests for the minimal PNG (RGBA) decoder (foilwright_ref.png, D-036).

Covers the fixtures generated by tools/make-png-fixtures.py: each of the 5
filter types individually, split IDAT, ancillary chunks, and (when present)
a real Ghostscript pngalpha output. Also covers the rejection paths --
D-036's whole point is that this decoder is deliberately narrow.
"""

from __future__ import annotations

import pathlib
import struct
import sys
import zlib

import pytest

REPO_ROOT = pathlib.Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT / "ref"))

from foilwright_ref import png

CASES_DIR = REPO_ROOT / "tests" / "cases" / "png"


def _pixel(pixels: bytes, width: int, x: int, y: int) -> tuple[int, int, int, int]:
    idx = (y * width + x) * 4
    return tuple(pixels[idx : idx + 4])


@pytest.mark.parametrize(
    "name",
    [
        "filter0_none.png",
        "filter1_sub.png",
        "filter2_up.png",
        "filter3_average.png",
        "filter4_paeth.png",
    ],
)
def test_filter_fixtures_decode_to_same_pixels(name: str) -> None:
    """All 5 filter fixtures encode the same underlying 16x16 pattern
    (tools/make-png-fixtures.py's _patterned_pixels); regardless of which
    filter type was used, decoding must recover identical pixels."""
    width, height, pixels = png.read_png_rgba(str(CASES_DIR / name))
    assert (width, height) == (16, 16)
    assert len(pixels) == 16 * 16 * 4

    reference_width, reference_height, reference_pixels = png.read_png_rgba(
        str(CASES_DIR / "filter0_none.png")
    )
    assert (width, height) == (reference_width, reference_height)
    assert pixels == reference_pixels


def test_idat_split_decodes() -> None:
    path = CASES_DIR / "idat_split.png"
    raw = path.read_bytes()
    idat_count = raw.count(b"IDAT")
    assert idat_count >= 3, "fixture must actually exercise multi-IDAT concatenation"

    width, height, pixels = png.read_png_rgba(str(path))
    assert (width, height) == (24, 24)
    assert len(pixels) == 24 * 24 * 4


def test_ancillary_chunks_are_skipped() -> None:
    path = CASES_DIR / "ancillary.png"
    raw = path.read_bytes()
    assert b"tEXt" in raw

    width, height, pixels = png.read_png_rgba(str(path))
    assert (width, height) == (12, 12)
    assert len(pixels) == 12 * 12 * 4


def test_gs_alpha_distinguishes_painted_white_from_untouched() -> None:
    """D-036's motivating case: alpha=255 (painted white) must be
    distinguishable from alpha=0 (nothing drawn)."""
    path = CASES_DIR / "gs_alpha.png"
    if not path.is_file():
        pytest.skip(
            "gs_alpha.png not present (Ghostscript was unavailable when fixtures were generated)"
        )

    width, height, pixels = png.read_png_rgba(str(path))
    assert (width, height) == (200, 200)

    # tools/make-png-fixtures.py draws a white rectfill at PostScript
    # coords 50,50 to 150,150 on a 200x200 page. PostScript origin is
    # bottom-left; PNG rows are top-down, so the painted square is
    # vertically flipped relative to PostScript y.
    painted = _pixel(pixels, width, 100, 100)
    untouched = _pixel(pixels, width, 5, 5)

    assert painted == (255, 255, 255, 255)
    assert untouched == (255, 255, 255, 0)


def test_rejects_bad_signature() -> None:
    with pytest.raises(png.PngFormatError, match="signature"):
        png._read_chunks(b"not a png at all")


def test_rejects_non_rgba_colour_type(tmp_path: pathlib.Path) -> None:
    # Colour type 2 = RGB (no alpha) at bit depth 8, 1x1, filter-None row.
    ihdr = struct.pack(">IIBBBBB", 1, 1, 8, 2, 0, 0, 0)
    raw = bytes([0, 0, 0, 0])  # filter byte + 1 RGB pixel
    idat = zlib.compress(raw)
    out = _assemble_png(ihdr, [idat])
    bad_path = tmp_path / "rgb.png"
    bad_path.write_bytes(out)

    with pytest.raises(png.PngFormatError, match="colour type"):
        png.read_png_rgba(str(bad_path))


def test_rejects_bad_bit_depth(tmp_path: pathlib.Path) -> None:
    ihdr = struct.pack(">IIBBBBB", 1, 1, 16, 6, 0, 0, 0)
    raw = bytes([0]) + bytes(8)  # filter byte + 1 RGBA16 pixel
    idat = zlib.compress(raw)
    out = _assemble_png(ihdr, [idat])
    bad_path = tmp_path / "16bit.png"
    bad_path.write_bytes(out)

    with pytest.raises(png.PngFormatError, match="bit depth"):
        png.read_png_rgba(str(bad_path))


def test_rejects_interlaced(tmp_path: pathlib.Path) -> None:
    ihdr = struct.pack(">IIBBBBB", 1, 1, 8, 6, 0, 0, 1)
    raw = bytes([0, 0, 0, 0, 0])
    idat = zlib.compress(raw)
    out = _assemble_png(ihdr, [idat])
    bad_path = tmp_path / "interlaced.png"
    bad_path.write_bytes(out)

    with pytest.raises(png.PngFormatError, match="interlace"):
        png.read_png_rgba(str(bad_path))


def test_rejects_bad_crc(tmp_path: pathlib.Path) -> None:
    ihdr = struct.pack(">IIBBBBB", 1, 1, 8, 6, 0, 0, 0)
    raw = bytes([0, 0, 0, 0, 0])
    idat = zlib.compress(raw)
    out = bytearray(_assemble_png(ihdr, [idat]))
    # Flip a bit inside the IHDR chunk's data (well before its CRC) without
    # touching its stored CRC value.
    out[20] ^= 0xFF
    bad_path = tmp_path / "badcrc.png"
    bad_path.write_bytes(bytes(out))

    with pytest.raises(png.PngFormatError, match="CRC"):
        png.read_png_rgba(str(bad_path))


def test_rejects_missing_idat(tmp_path: pathlib.Path) -> None:
    ihdr = struct.pack(">IIBBBBB", 1, 1, 8, 6, 0, 0, 0)
    out = _assemble_png(ihdr, [])
    bad_path = tmp_path / "noidat.png"
    bad_path.write_bytes(out)

    with pytest.raises(png.PngFormatError, match="IDAT"):
        png.read_png_rgba(str(bad_path))


def _chunk(chunk_type: bytes, data: bytes) -> bytes:
    return (
        struct.pack(">I", len(data))
        + chunk_type
        + data
        + struct.pack(">I", zlib.crc32(chunk_type + data) & 0xFFFFFFFF)
    )


def _assemble_png(ihdr: bytes, idat_parts: list[bytes]) -> bytes:
    parts = [png._PNG_SIGNATURE, _chunk(b"IHDR", ihdr)]
    parts.extend(_chunk(b"IDAT", part) for part in idat_parts)
    parts.append(_chunk(b"IEND", b""))
    return b"".join(parts)
